### ISSUE TITLE
terms checkbox uncheck too early

### ISSUE THREAD

**Issue by mwenell** [Webmie/App-and-Extension-2019#14]
PROBLEM

When you click accept terms button, it first clear cechings of checkboxes and them fadeOut. Should first fadeOut and then clear checkboxex.

SOLUTION

Clear checkboxes in callback of fadeOut.

**Comment by Njugen** [comment]
Fixed. The checkboxes and other "resets" now happens once the fadeOut has finished successfully (callback)
