### ISSUE TITLE
Cancel of VPN settings do not open modal to confirm it

### ISSUE THREAD

**Issue by mwenell** [Webmie/App-and-Extension-2019#15]
PROBLEM

If you click "påbörja ... VPN" it opens the popup to asking "allow" VPN congigs.

If you click "cancel", it close the popup and you can only click again "Påbörja ... VPN". The modal askin yes/no for the cancelling is not anymore there.

**Comment by Njugen** [comment]
Has forwarded this to johannes

**Comment by Njugen** [comment]
> @Johannes Ylönen ok, thanks for confirming. It seems you were right about iOS calling the failure callback at failure. The problem boiled down to z-index working slightly differently in iOS than Android. As it turned out, the modal worked... it was just not visible and got hidden behind other elements without me seeing it. This has now been resolved...

Copying my response to Johannes from Slack. It turned out everything related to this was css error and how it is interpreted in the iphone.

**Comment by johannes** [comment]
Please be careful with highlights. :)
