### ISSUE TITLE
Desktop Join Page does not have correct button ID

### ISSUE THREAD

**Issue by Njugen** [Webmie/App-and-Extension-2019#25]
Desktop join page should have a button with id "open_svenska_internetpanelen". This button is missing at the moment. 

Clicking a button using this id will make the extension open code entrance page with prefilled code. (open_svenska_internetpanelen in both production and alpha join page for now)

**Comment by mwenell** [comment]
New join page for survey browser app will be in new homepage when it is ready.

**Comment by Njugen** [comment]
This is more for "Survey Browser"
