### ISSUE TITLE
Platform and code URL tags do not work

### ISSUE THREAD

**Issue by mwenell** [Webmie/App-and-Extension-2019#27]
PROBLEM
(desktop test)

The homepage and complete links need to have following TAGs:
{{fid}}  works ok
{{src}} works ok except it is givin None if no src, it should give empty
{{platform}} not working, should give platform as android | ios | desktop
{{code}}

SOLUTION

Make these all tags work in both complete page and homepage links.

NOTE: {{code}} or {{src}} is not launch stopper, but {{platform}} is if it does not work in complete page link (???).

**Comment by Njugen** [comment]
Platform seems to work fine. What about {{code}}? When FID == code nowadays?

**Comment by mwenell** [comment]
{{code}} is not needed.

**Comment by Njugen** [comment]
then I close this issue.
