### ISSUE TITLE
Pause - Record feature

### ISSUE THREAD

**Issue by mwenell** [Webmie/App-and-Extension-2019#53]
The user need to be able to pause the tracking in each membership as s/he wants to do. The problem is that in ongoing surveys as MMS or Syno you need to be able to decide when you are active and when not.

Functionality

- The button is a record button if the recording is not on -> click will start recording and makes the membership active
- The button is a pause button if recording is on -> clcik will pause the recording and makes the membership disabled

**Comment by Njugen** [comment]
Feature is now implemented
